
version: '3'
services:
  database:
    image: mysql:5.7
    container_name: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: examv2thouraya
    ports:
      - 3306:3306
    networks:
      - AppNet

  ExamThourayaS2-0.0.1-SNAPSHOT:
    image: bnasro/devopsproject
    container_name: ExamThourayaS2-0.0.1-SNAPSHOT
    ports:
      - 8083:8083
    depends_on:
      - database
    networks:
      - AppNet
    restart: on-failure
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url"  : "jdbc:mysql://mysql:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
            "spring.datasource.username" : "$MYSQLDB_USER",
            "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
            "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
            "spring.jpa.hibernate.ddl-auto" : "update"
          }'
networks:
  AppNet: