
version: '3'
services:
  database:
    image: mysql5
    container_name: mysql5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: examv2thouraya
    ports:
      - 3306:3306
    networks:
      - AppNet

  ExamThourayaS2-0.0.1-SNAPSHOT:
    image: bnasro/devopsproject
    container_name: ExamThourayaS2
    ports:
      - 8083:8083
    depends_on:
      - database
    networks:
      - AppNet
    restart: on-failure
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/examv2thouraya?useSSL=false",
       		"spring.datasource.username" : "root",
       		"spring.datasource.password" : "root",
       		"spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
       		"spring.jpa.hibernate.ddl-auto" : "update"}'
          
networks:
  AppNet: